In [1]:
import torch

In [2]:
#创建一个5x3的未初始化的张量tensor
x = torch.empty(5,3)
print(x)

tensor([[1.1708e-19, 7.2128e+22, 9.2216e+29],
        [7.5546e+31, 1.6932e+22, 3.0728e+32],
        [2.9514e+29, 2.8940e+12, 7.5338e+28],
        [1.8037e+28, 3.4740e-12, 1.7743e+28],
        [2.0535e-19, 1.4609e-19, 7.5630e+28]])


In [3]:
#创建一个5x3的随机初始化的张量tensor，rand/randn为均匀或标准分布
x = torch.rand(5,3)
print(x)

tensor([[0.5051, 0.7981, 0.0038],
        [0.6390, 0.3009, 0.3095],
        [0.3113, 0.4323, 0.3865],
        [0.7518, 0.9457, 0.2597],
        [0.9955, 0.7436, 0.8702]])


In [4]:
#创建一个5x3的long型全0的张量tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#直接根据数据建模
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
#返回的tensor默认具有相同的dtype和device，ones为全1的tensor
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

#指定新的数据类型
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1648,  1.4240,  0.2190],
        [-1.3811, -0.8536,  1.2616],
        [ 0.5270, -0.5925,  0.4442],
        [ 0.2477, -0.0329, -0.5279],
        [ 2.1883, -0.3917, -0.5633]])


In [8]:
#获取tensor的形状,返回的torch.Size是一个元组
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [9]:
#加法操作
y = torch.rand(5,3)

print(x + y)

print(torch.add(x,y))

result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

y.add_(x)
print(y)

tensor([[ 1.6472,  1.4311,  0.3658],
        [-0.8817, -0.0277,  1.9558],
        [ 0.6568,  0.0114,  1.0558],
        [ 0.6816,  0.3836,  0.4358],
        [ 3.1586, -0.2257,  0.4119]])
tensor([[ 1.6472,  1.4311,  0.3658],
        [-0.8817, -0.0277,  1.9558],
        [ 0.6568,  0.0114,  1.0558],
        [ 0.6816,  0.3836,  0.4358],
        [ 3.1586, -0.2257,  0.4119]])
tensor([[ 1.6472,  1.4311,  0.3658],
        [-0.8817, -0.0277,  1.9558],
        [ 0.6568,  0.0114,  1.0558],
        [ 0.6816,  0.3836,  0.4358],
        [ 3.1586, -0.2257,  0.4119]])
tensor([[ 1.6472,  1.4311,  0.3658],
        [-0.8817, -0.0277,  1.9558],
        [ 0.6568,  0.0114,  1.0558],
        [ 0.6816,  0.3836,  0.4358],
        [ 3.1586, -0.2257,  0.4119]])


In [10]:
#索引操作，类似于numpy的索引
#注意索引出来的结果与原数据共享内存，索引结果修改了，原数据也会跟着被修改

y = x[0, :]
y += 1
print(y)
print(x[0, :])

tensor([2.1648, 2.4240, 1.2190])
tensor([2.1648, 2.4240, 1.2190])


In [11]:
#改变形状,view只改变了这个张量的观察角度，内部数据没有改变
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [13]:
#item可以将一个标量tensor转换成一个python数字
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9073])
0.9072679281234741
