In [9]:
%matplotlib inline
import torch
import numpy as np
import sys
sys.path.append('..')
import d2lzh_pytorch as d2l

In [10]:
# 生成人工数据集 ，给定样本特征x ，使用三阶多项式函数生成样本标签y
# y = 1.2x - 3.4x^2 + 5.6x^3 + 5 + c
# 噪声项 c 服从均值为0，标准差为0.01的正态分布

n_train, n_test, true_w, true_b = 100, 100, [1.2, -3.4, 5.6], 5
features = torch.randn((n_train + n_test, 1))

# 将张量x,x^2,x^3拼接联系在一起
poly_features = torch.cat((features, torch.pow(features, 2), torch.pow(features, 3)), 1)

labels = (true_w[0] * poly_features[:, 0] + true_w[1] * poly_features[:, 1] + true_w[2] * poly_features[:, 2] + true_b)
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)

In [11]:
print(features.size())
print(poly_features.size())
print(labels.size())

features[:2], poly_features[:2], labels[:2]

torch.Size([200, 1])
torch.Size([200, 3])
torch.Size([200])


(tensor([[-0.0207],
         [-0.6851]]),
 tensor([[-2.0705e-02,  4.2868e-04, -8.8756e-06],
         [-6.8508e-01,  4.6933e-01, -3.2153e-01]]),
 tensor([4.9702, 0.7755]))

In [20]:
#定义作图函数
def semilogy(x_vals, y_vals, x_label, y_label, 
             x2_vals=None, y2_legend=None, figsize=(3.5, 2.5)):
    d2l.set_figsize(figsize)
    d2l.plt.xlabel(x_label)
    d2l.plt.ylabel(y_label)
    d2l.plt.semilogy(x_vals, y_vals)
    if x2_vals and y2_vals:
        d2l.plt.semilogy(x2_vals, y2_vals, linestyle=':')
        d2l.plt.legend(legend)

In [32]:
num_epochs, loss = 100, torch.nn.MSELoss()

def fit_and_plot(train_features, test_features, train_labels, test_labels):
    net = torch.nn.Linear(train_features.shape[-1], 1)
    # 通过Linear文档可知，pytorch已经将参数初始化了，所以我们这里就不手动初始化了

    batch_size = min(10, train_labels.shape[0])    
    dataset = torch.utils.data.TensorDataset(train_features, train_labels)
    train_iter = torch.utils.data.DataLoader(dataset, batch_size, shuffle=True)

    optimizer = torch.optim.SGD(net.parameters(), lr=0.01)
    train_ls, test_ls = [], []
    for _ in range(num_epochs):
        for X, y in train_iter:
            l = loss(net(X), y.view(-1, 1))
            optimizer.zero_grad()
            l.backward()
            optimizer.step()
        train_labels = train_labels.view(-1, 1)
        test_labels = test_labels.view(-1, 1)
        train_ls.append(loss(net(train_features), train_labels).item())
        test_ls.append(loss(net(test_features), test_labels).item())
    print('final epoch: train loss', train_ls[-1], 'test loss', test_ls[-1])
    semilogy(range(1, num_epochs + 1), train_ls, 'epochs', 'loss',
             range(1, num_epochs + 1), test_ls,['train','test'])
    print('weight:', net.weight.data,
          '\nbias:', net.bias.data)

In [33]:
fit_and_plot(poly_features[:n_train, :], poly_features[n_train:, :], 
            labels[:n_train], labels[n_train:])

final epoch: train loss 6.0769834817619994e-05 test loss 0.0001229446497745812


ValueError: Key figure.figsize: Could not convert tensor([[   4.9702],
        [   0.7755],
        [   5.9491],
        [  40.8281],
        [ -29.7226],
        [  -4.9296],
        [   5.2034],
        [  17.0397],
        [   5.6331],
        [ -14.9966],
        [  10.8676],
        [  27.7880],
        [  29.6420],
        [  34.0326],
        [  21.0908],
        [  11.6101],
        [   4.3396],
        [   5.6087],
        [   5.1561],
        [   5.1506],
        [   4.9802],
        [   5.6847],
        [  -8.4813],
        [   6.4018],
        [   4.3325],
        [   4.9282],
        [  11.3135],
        [   5.1759],
        [   5.1293],
        [  24.3923],
        [ 212.9212],
        [   5.9929],
        [ -15.6709],
        [   2.1853],
        [   5.3006],
        [   3.5576],
        [  25.0771],
        [  -4.2024],
        [   5.0877],
        [   4.5528],
        [   5.4271],
        [ -25.6411],
        [   0.7366],
        [   5.0249],
        [ -11.3753],
        [   7.6511],
        [  53.9194],
        [   4.8798],
        [ -37.4269],
        [   5.1693],
        [  -2.0070],
        [   1.4944],
        [  58.8091],
        [   0.7585],
        [ -17.2258],
        [   8.9076],
        [  32.0676],
        [   4.5055],
        [   6.0849],
        [   6.1485],
        [   1.4298],
        [   3.6431],
        [   4.8161],
        [-122.1467],
        [  20.1830],
        [  -0.8395],
        [  12.2470],
        [  10.3224],
        [  17.5297],
        [-177.2251],
        [   5.0581],
        [   1.3656],
        [   1.3131],
        [   5.1375],
        [ -30.6388],
        [   4.7362],
        [ -17.2037],
        [   5.2777],
        [   7.7508],
        [   6.8574],
        [   5.3426],
        [   4.7263],
        [  -3.9709],
        [   5.4931],
        [   1.8631],
        [  17.7867],
        [   5.7085],
        [   5.8020],
        [   1.4648],
        [   5.2109],
        [   5.0256],
        [   4.9583],
        [   3.9507],
        [   5.4871],
        [   6.0907],
        [   3.8284],
        [   4.0011],
        [   5.2399],
        [  20.5912],
        [   4.4776]]) to float

In [23]:
fit_and_plot(features[:n_train, :], features[n_train:, :], labels[:n_train],
             labels[n_train:])

final epoch: train loss 462.03460693359375 test loss 158.6803741455078


ValueError: Key figure.figsize: Could not convert 'train' to float