In [1]:
import torch
from torch import nn

x = torch.ones(3)
torch.save(x, 'x.pt')

In [2]:
x2 = torch.load('x.pt')
x2

tensor([1., 1., 1.])

In [3]:
y = torch.zeros(4)
torch.save([x, y], 'xy.pt')
xy_list = torch.load('xy.pt')
xy_list

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

In [4]:
torch.save({'x': x, 'y': y}, 'xy_dict.pt')
xy = torch.load('xy_dict.pt')
xy

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}

In [5]:
#state_dict是一个从参数名称隐射到参数Tesnor的字典对象

#只有具有可学习参数的层(卷积层、线性层等)才有state_dict中的条目

class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)
        self.act = nn.ReLU()
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)

net = MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.3185, -0.3042, -0.5369],
                      [ 0.2602, -0.5035, -0.5198]])),
             ('hidden.bias', tensor([-0.3551,  0.3888])),
             ('output.weight', tensor([[-0.4569, -0.3650]])),
             ('output.bias', tensor([-0.4818]))])

In [6]:
#优化器(optim)

optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'params': [0, 1, 2, 3]}]}

In [12]:
# 保存和加载模型参数

# torch.save(model.state_dict(), PATH) 
# model = TheModelClass(*args, **kwargs)
# model.load_state_dict(torch.load(PATH))

X = torch.randn(2, 3)
Y = net(X)

PATH = "./net.pt"
torch.save(net.state_dict(), PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y

tensor([[True],
        [True]])

In [13]:
# 保存和加载整个模型

# torch.save(model, PATH)
# model = torch.load(PATH)